// The Cicada Closet — 3D hero, mesh build.
//
// The sheet is her paper with the lettering printed on it. The cicada, the vines and the gold
// orbs are a real relief mesh lying on that sheet — generated by Hunyuan3D from a cutout of her
// artwork, and skinned with that same artwork, so the wings and vines have thickness and throw
// their own shading as the camera moves. Her linework is the texture; the geometry only gives
// it depth. A perspective camera flies to the keyhole in the cicada's thorax and through.
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';

const host = document.getElementById('stage3d');
if (host) {
  const KY = 0.3665;                       // keyhole centre, as a fraction of the logo
  const PAPER = 3.0;                       // paper size in world units
  // where the relief sits on the paper: the cutout's box in logo fractions (from the build script)
  const BOX = { x0: 0.0997, x1: 0.8966, y0: 0.1200, y1: 0.7396 };
  const prefersReduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const small = Math.min(innerWidth, innerHeight) < 700 || (devicePixelRatio || 1) < 1.5;

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio || 1, small ? 1.5 : 2));   // lit mesh: cap phones
  renderer.setSize(innerWidth, innerHeight);
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  host.appendChild(renderer.domElement);

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, 0.01, 60);

  // one warm room light, keyed from the upper left like the paper's own grain
  scene.add(new THREE.HemisphereLight(0xfff3df, 0x6a4a30, 1.05));
  const key = new THREE.DirectionalLight(0xfff6e8, 1.35); key.position.set(-2.2, 3.2, 4.5); scene.add(key);
  const fill = new THREE.DirectionalLight(0xffe2b8, 0.35); fill.position.set(3, 0.8, 2.5); scene.add(fill);

  // the dark behind the keyhole: a shaft, narrower than the sheet, DoubleSide so it holds once inside
  const well = new THREE.Mesh(
    new THREE.BoxGeometry(PAPER * 0.55, PAPER * 0.55, 9),
    new THREE.MeshBasicMaterial({ color: 0x0b0806, side: THREE.DoubleSide })
  );
  well.position.z = -4.55;
  scene.add(well);

  // her paper: kraft with the lettering printed; the relief's footprint is bare paper underneath
  const paper = new THREE.Mesh(
    new THREE.PlaneGeometry(PAPER, PAPER),
    new THREE.MeshBasicMaterial({ transparent: true, side: THREE.DoubleSide })
  );
  scene.add(paper);

  const field = new THREE.Mesh(
    new THREE.PlaneGeometry(PAPER * 9, PAPER * 9),
    new THREE.MeshBasicMaterial({ color: 0xab7e56 })
  );
  field.position.z = -0.30;
  scene.add(field);

  const aimY = (0.5 - KY) * PAPER;
  well.position.y = aimY;

  const relief = new THREE.Group();
  scene.add(relief);

  let paperReady = false, meshReady = false;
  const announce = () => { if (paperReady && meshReady) host.dispatchEvent(new CustomEvent('hero3d:ready')); };

  const tl = new THREE.TextureLoader();
  tl.load(host.dataset[small ? 'paper2k' : 'paper4k'], (t) => {
    t.colorSpace = THREE.SRGBColorSpace;
    t.anisotropy = Math.min(8, renderer.capabilities.getMaxAnisotropy());
    paper.material.map = t; paper.material.needsUpdate = true;
    paperReady = true; announce();
  });
  tl.load(host.dataset.kraft, (t) => {
    t.colorSpace = THREE.SRGBColorSpace;
    t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.set(16, 16);
    field.material.map = t; field.material.color.set(0xffffff); field.material.needsUpdate = true;
  });

  const gltf = new GLTFLoader(); gltf.setMeshoptDecoder(MeshoptDecoder);   // geometry ships meshopt-compressed
  gltf.load(host.dataset.mesh, (g) => {
    const root = g.scene;
    const box = new THREE.Box3().setFromObject(root), size = new THREE.Vector3(), c = new THREE.Vector3();
    box.getSize(size); box.getCenter(c);
    root.position.sub(c);                                   // centre it on its own box
    const s = (BOX.x1 - BOX.x0) * PAPER / size.x;           // fit its width to the cutout's footprint
    relief.scale.setScalar(s);
    relief.position.set(((BOX.x0 + BOX.x1) / 2 - 0.5) * PAPER,
                        (0.5 - (BOX.y0 + BOX.y1) / 2) * PAPER,
                        size.z * s / 2 + 0.006);           // its back face rests on the sheet
    root.traverse((o) => {
      if (o.isMesh && o.material) {
        o.material.side = THREE.FrontSide;
        // matte: the generated material carried gloss, and the black keyhole face threw a
        // specular glint right as the camera arrived at it
        o.material.roughness = 1.0; o.material.metalness = 0.0;
        if (o.material.metalnessMap) o.material.metalnessMap = null;
        if (o.material.roughnessMap) o.material.roughnessMap = null;
        if (o.material.map) { o.material.map.colorSpace = THREE.SRGBColorSpace; o.material.map.anisotropy = 8; }
        o.material.needsUpdate = true;
      }
    });
    relief.add(root);
    meshReady = true; announce();
  }, undefined, () => { meshReady = true; announce(); });   // no mesh: the flat sheet still works

  let restZ = 4.35, restLift = 0, restShift = 0;
  function frame(p) {
    const e = prefersReduced ? 0 : Math.pow(p, 0.88);
    const k = Math.pow(Math.max(0, 1 - e / 0.68), 1.5);
    const lift = restLift * k, side = restShift * k;
    const z = restZ - e * (restZ + 0.70);
    camera.position.set(-side, aimY * (1 - e * 0.15) + lift, z);
    camera.lookAt(-side, aimY + lift, -1);
    paper.rotation.x = (1 - e) * 0.085;
    field.rotation.x = paper.rotation.x;
    // the relief rides the sheet, and turns a few degrees across the push so its depth reads
    relief.rotation.x = paper.rotation.x;
    relief.rotation.y = prefersReduced ? 0 : (0.5 - e) * 0.10;
    renderer.render(scene, camera);
  }

  function resize() {
    camera.aspect = innerWidth / innerHeight;
    camera.fov = camera.aspect < 0.85 ? 58 : 42;
    const wide = camera.aspect >= 1.25, mid = camera.aspect >= 0.85;
    restZ     = wide ? 3.80  : mid ? 4.05  : 4.35;
    restLift  = wide ? -0.30 : mid ? -0.12 : 0.08;
    restShift = wide ? 0.95  : 0;
    camera.updateProjectionMatrix();
    renderer.setSize(innerWidth, innerHeight);
  }
  addEventListener('resize', resize);
  resize();

  window.__hero3d = { frame, isReady: () => paperReady && meshReady };
}
